export default [
  'Learning is a Lifelong Process',
  'I am always ready to learn although I do not always like being taught.',
  'Live as if you were to die tomorrow. Learn as if you were to live forever.',
  'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.',
  'Tell me and I forget, teach me and I may remember, involve me and I learn.',
  'Develop a passion for learning. If you do, you will never cease to grow.',
  'You don’t understand anything until you learn it more than one way.',
  'He who laughs most, learns best.',
  'Spoon feeding in the long run teaches us nothing but the shape of the spoon.',
  'In the end we retain from our studies only that which we practically apply.',
  'Change is the end result of all true learning.',
  'The beautiful thing about learning is nobody can take it away from you.',
  'Being a student is easy. Learning requires actual work.',
  'If you think education is expensive, try estimating the cost of ignorance.',
  'The great aim of education is not knowledge but action.',
  'Study without desire spoils the memory, and it retains nothing that it takes in.',
  'Education without application is just entertainment.',
  'I am still learning.',
  'Recipes tell you nothing. Learning techniques is the key.',
  'The ability to speak exactly is intimately related to the ability to know exactly.',
  'It is what we know already that often prevents us from learning.',
  'Learning is synthesizing seemingly divergent ideas and data.',
  'It’s what you learn after you know it all that counts.',
  'I never learned from a man who agreed with me.',
  'You don’t learn to walk by following rules. You learn by doing, and by falling over.',
  'A man who asks is a fool for five minutes. A man who never asks is a fool for life.',
  'A moment’s insight is sometimes worth a life’s experience.',
  'The most useful piece of learning for the uses of life is to unlearn what is untrue.',
  'The whole purpose of education is to turn mirrors into windows.',
  'Curiosity is the wick in the candle of learning.',
  'Leadership and learning are indispensable to each other.',
  'Change is the end result of all true learning.',
  'The expert in anything was once a beginner.',
]
